dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install requests
  - pip install python-dotenv
  - pip install pandas
  - pip install matplotlib
  - pip install pytest

script:
  - pytest
